/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NameComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLNameComponentElement extends Components.NameComponent, HTMLStencilElement {
    }
    var HTMLNameComponentElement: {
        prototype: HTMLNameComponentElement;
        new (): HTMLNameComponentElement;
    };
    interface HTMLElementTagNameMap {
        "name-component": HTMLNameComponentElement;
    }
}
declare namespace LocalJSX {
    interface NameComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "name-component": NameComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "name-component": LocalJSX.NameComponent & JSXBase.HTMLAttributes<HTMLNameComponentElement>;
        }
    }
}
